### ISSUE TITLE
HostEnvironment should be resolved lazily for Liquid module

### ISSUE THREAD

**Issue by sebastienros** [OrchardCoreContrib/OrchardCoreContrib.Modules#104]
https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/blob/main/src/OrchardCoreContrib.Liquid/Startup.cs#L18

This is expensive since it's called for each accessor in a template. This should be executed only if the property matches. This should be in a local function and invoked when necessary.

**Comment by hishamco** [comment]
Thanks, hope to fix it soon

**Comment by hishamco** [comment]
Thanks, hope to fix it soon

**Comment by hishamco** [comment]
Seb, what if I use `IHostEnvironment` from the DI through the constructor, so it will be executed during enabling the module

**Comment by sebastienros** [comment]
Maybe it can be resolved outside of the lambda, once.
