### ISSUE TITLE
Wrong project website, source repository URLs in NuGet packages

### ISSUE THREAD

**Issue by Piedone** [OrchardCoreContrib/OrchardCoreContrib.Modules#21]
See e.g. here: https://www.nuget.org/packages/OrchardCoreContrib.ContentPreview/1.0.0-beta1

**Comment by hishamco** [comment]
Thanks Zoltan it's my fault that I copied the metadata from another project that I didn't publish yet

I will fix it ASAP

**Comment by hishamco** [comment]
Fixed in https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/commit/8d63a6f513c1d26726d52faae2f019187167eb75

Seems I need to republish the packages again if NuGet not allow us to change the package metadata

Thanks
