### ISSUE TITLE
Add GrapesJs Editor

### ISSUE THREAD

**Issue by hishamco** [OrchardCoreContrib/OrchardCoreContrib.Modules#35]
Adding Graphes JS editor in HTML Module

/cc @kudryavtsevda

**Comment by kudryavtsevda** [comment]
Thanks for looping me, I am waiting to check your module

**Comment by hishamco** [comment]
I already have a WIP PR, hope to submit it ASAP

**Comment by kudryavtsevda** [comment]
Could you provide me link regarding to this PR? if it is possible

**Comment by hishamco** [comment]
I will push a WIP PR today, I will keep you updated

**Comment by hishamco** [comment]
@kudryavtsevda a WIP PR is created

**Comment by kudryavtsevda** [comment]
> @kudryavtsevda a WIP PR is created

Thanks, let me check
BTW, do you know when it will be approved?

**Comment by hishamco** [comment]
For OCC I can publish a beta release but it needs some work to make the components show up in the blocks section

**Comment by hishamco** [comment]
You can fork the repo and try the module and it will be nice if you want to push some commits

**Comment by kudryavtsevda** [comment]
I have been playing with your module and noticed that 1) uploaded images are not saved 2) background colors are not saved and 3) control panel in the right top cornet doesn't work at all (no preview, no code review)
![image](https://user-images.githubusercontent.com/4447809/156005358-779fdf4a-6d18-4d48-af0d-e8bbeb5a147b.png)

may be I did something wrong?

**Comment by hishamco** [comment]
Seems I disabled the storage. Regarding the last two points I notice that while I'm developing, I presume this a script issues, coz when I use GrapesJs in a blank html it works. I need to figure out why, if you can help on this it's much appreciated

That's why I told you we need a lot of work here, more interestingly adding components in blocks section

**Comment by kudryavtsevda** [comment]
@hishamco I figured out that html body part should be setup with disabled if you want to allow to use local storage of grapes-js. otherwiese it may be required to setup remote storage. so as a result I managed to show my images uploaded by grapes-js from orchard end-user perspective. 
![image](https://user-images.githubusercontent.com/4447809/156231048-9ed982b9-0557-4f1b-b0ea-7989964c9c47.png)

**Comment by hishamco** [comment]
Thanks, I really forgot to uncheck the santize option, but still I'm not sure sure why the preview and other icons not working

**Comment by kudryavtsevda** [comment]
I will go through "get started" https://grapesjs.com/docs/getting-started.html#import-the-library and I bet I will find answer there

**Comment by hishamco** [comment]
BTW I already downloaded the latest version, hope to use CDN resources in the upcoming update

**Comment by kudryavtsevda** [comment]
Have you noticed that these buttons are not working? 
![image](https://user-images.githubusercontent.com/4447809/156399591-2da097c9-4729-4153-a7d9-2b3b150664d5.png)

**Comment by hishamco** [comment]
Let me know the content that you entered in the editor, so I can check. Probably the issue comes from scripts collision as I mentioned [above](https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/issues/35#issuecomment-1054430413)

**Comment by kudryavtsevda** [comment]
it contains only such block: <div data-gjs-type="text">Insert your text here</div>
![image](https://user-images.githubusercontent.com/4447809/156407189-61208be2-e103-4cce-a4b5-e319b8778a4d.png)

**Comment by hishamco** [comment]
Custom block?

**Comment by kudryavtsevda** [comment]
Like this one
![image](https://user-images.githubusercontent.com/4447809/156424102-640e10ed-92c5-4f1d-8291-82e85856e579.png)

**Comment by kudryavtsevda** [comment]
I noticed that toolbar button is replaced and commented in orchard due to some reason 
![image](https://user-images.githubusercontent.com/4447809/156433792-6c9bb9a6-e934-4a59-9aa2-e7ff6e8391d7.png)
compare with properly working toolbar here:
![image](https://user-images.githubusercontent.com/4447809/156434123-bcea6905-f51b-45bf-a747-534c156316fc.png)

**Comment by hishamco** [comment]
As I told you something weired happenning here, it needs time to investigate

**Comment by kudryavtsevda** [comment]
![image](https://user-images.githubusercontent.com/4447809/156563879-01783607-8d73-44cc-ac66-ca1371a0f6be.png)
I created new admin theme and disabled this two lines. after that grapes js was working BUT some styles were disappeared. 
I fixed it by adding new awesome-font of 4.7.0 version with small fix here 
![image](https://user-images.githubusercontent.com/4447809/156564243-2e483a4f-b888-44b8-a439-7566219115da.png)
and I attached that awesomestyle. you can see it on 24th line in the first screenshot

**Comment by hishamco** [comment]
> I fixed it by adding new awesome-font of 4.7.0 version with small fix here

Why we need to add `.fas` if you updated the font-awesome version?

**Comment by kudryavtsevda** [comment]
> > I fixed it by adding new awesome-font of 4.7.0 version with small fix here
> 
> Why we need to add `.fas` if you updated the font-awesome version?

because default orchard admin theme uses 'fas' instead of 'fa'
Default admin theme without any changes:
![image](https://user-images.githubusercontent.com/4447809/156588109-36d5bca3-f417-4fcb-b3e8-18ba3ce8df39.png)

After adding 'fas' into css. As you see grapesJs is working properly in conjuction with orchard admin theme
![image](https://user-images.githubusercontent.com/4447809/156588792-41f4fadf-08fd-4030-ac03-b7eec460bb1f.png)

I don't claim that my solution is 100% correct BUT I found the reason and workaround

**Comment by hishamco** [comment]
Thanks so much for your efforts, we need to add your changes in the our HTML module

**Comment by hishamco** [comment]
I think upgrading the `OC.Resources` should solve the font awesome issue

**Comment by hishamco** [comment]
@kudryavtsevda could you surround the editor using iframe, then there's no need to introduce a new theme or removing a scripts from the admin theme

**Comment by kudryavtsevda** [comment]
> @kudryavtsevda could you surround the editor using iframe, then there's no need to introduce a new theme or removing a scripts from the admin theme

Interesting idea. I thought about it as well. I will try on Wednesday
BTW, I managed apply grapes js demo preset with grapes js web-plugin from the demo page. It looks great

**Comment by hishamco** [comment]
Hope if you can participate on this PR, because I'm quite busy with Data Localization Module. BTW I updated the related PR with the latest OC bits

Points to consider if you want to participate:

- Use iframe or Partial to isolate the GrapesJS Editor
- Add resources if it's needed as a part of this module

If all goes well then we can use OC widgets as blocks elements

**Comment by hishamco** [comment]
You can fork the repo and work on top of my PR, please let me know if you need help. I'm sure this will be one of the greate modules that we will have

**Comment by hishamco** [comment]
> BTW, I managed apply grapes js demo preset with grapes js web-plugin from the demo page. It looks great

Oh really, hope if you can share a GIF screenshot

**Comment by kudryavtsevda** [comment]
> Partial to isolate the GrapesJS Editor

Could you explain how to leverage partial views in OC? I thought it would be the same part of the DOM and would not help with CSS collisions

**Comment by hishamco** [comment]
Simple partial that contains iframe just to make the UI simple and clear

**Comment by kudryavtsevda** [comment]
> Oh really, hope if you can share a GIF screenshot

Sorry for being late. I have a tough schedule. You can see my results here
![screen-capture (1)](https://user-images.githubusercontent.com/4447809/157466990-bcae7bfc-a6ea-41b7-b1b2-1038155c731b.gif)

**Comment by hishamco** [comment]
Very nice, did you bring the components / blocks from GrapesJS itself? I think we need to extend that in OC. This will be one of the coolest modules in OCC, the credits goes for you ;)

Thanks, hope to see some commits in the associated PR, or you can start another one

**Comment by hishamco** [comment]
So let us keep this going, by fixing the scripts issues, make the editor works as expected, then we can think about the components or blocks

**Comment by kudryavtsevda** [comment]
I am trying to move grapes js into iframe as you asked me and I almost done BUT suddenly I was stuck.
Can I ask you to review these problems regarding GrapesJS module?
https://github.com/OrchardCMS/OrchardCore/discussions/11364 
https://github.com/OrchardCMS/OrchardCore/discussions/11362

May be you have an idea?

**Comment by hishamco** [comment]
Sure

**Comment by kudryavtsevda** [comment]
> Very nice, did you bring the components / blocks from GrapesJS itself? I think we need to extend that in OC. This will be one of the coolest modules in OCC, the credits goes for you ;)
> 
> Thanks, hope to see some commits in the associated PR, or you can start another one

I tried to commit changes regarding https://github.com/OrchardCMS/OrchardCore/discussions/11364 in that PR but I got 403 error access denied. But I bet you can do it without my assistance

**Comment by hishamco** [comment]
No problem I can change the Id and commit into my PR, just try to complete what you have started and keep me posted, then I can merge my PR followed by another PR that contains your changes. If you need to start a new PR no problem I can close mine

Thanks

**Comment by hishamco** [comment]
BTW @kudryavtsevda seems you miss to decorate your controller with the `Feature` attribute, I already use the same thing in OCC.Users module

**Comment by hishamco** [comment]
Any updates on this?

**Comment by kudryavtsevda** [comment]
We solved it on friday when I figured out that feature id should be the same as module name

**Comment by kudryavtsevda** [comment]
I believe you but I haven't tried

**Comment by hishamco** [comment]
Anyway, could you please let me the progress of this module, coz we need to publish a beta release at least. Please let me know if you have a branch in your forked repo

**Comment by kudryavtsevda** [comment]
> Anyway, could you please let me the progress of this module, coz we need to publish a beta release at least. Please let me know if you have a branch in your forked repo

as I said before I tried to commit right into your PR but it was not succesful due to lack of permissions

**Comment by hishamco** [comment]
Could you please create a branch on your repo, then I can commit what I have and let you create a new PR

**Comment by hishamco** [comment]
@kudryavtsevda any progress on this? Could you please share what you did here, so I can help if it's possible

**Comment by kudryavtsevda** [comment]
@hishamco yep. please see my pr https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/pull/51

**Comment by hishamco** [comment]
I merged the intial work that started by us, hopefully if you can address that two issues, then we can release an a beta release soon

**Comment by kudryavtsevda** [comment]
@hishamco check it out https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/pull/54

I can't reproduce unsuccessful saving into database. I see all my changes in db

**Comment by hishamco** [comment]
> I can't reproduce unsuccessful saving into database. I see all my changes in db

Could you please share a GIF screenshot showing how to add 2 or 3 columns add an image and simple text and hit save

**Comment by kudryavtsevda** [comment]
check it out

![screen-capture (2)](https://user-images.githubusercontent.com/4447809/159552232-60a8a3ec-47dc-4967-9132-54b4a96baeb6.gif)

**Comment by hishamco** [comment]
I will need to double check in my laptop, one more thing do you think that we need add anything else for now or we can ship the first beta release

Still I believe adding the OC widgets into the blocks will be a good enhancement

**Comment by hishamco** [comment]
You are right, everything is looks good

**Comment by hishamco** [comment]
FYI https://www.nuget.org/packages/OrchardCoreContrib.Html/1.0.0-beta1

**Comment by hishamco** [comment]
@[kudryavtsevda](https://github.com/kudryavtsevda) it would be nice if you demo this feature in the upcoming OC standup meeting, thanks for the great work

**Comment by kudryavtsevda** [comment]
@hishamco could you tell me about it more?

**Comment by hishamco** [comment]
The Orchard Core is doing a standup meeting almost every Tuesday, the team show the current status, discussing topics and show demos, please check https://orchardcore.net/ to get the Microsoft Teams link

Also you can check the previous videos on Lombiq YouTube channel

**Comment by hishamco** [comment]
I think it's a good chance to show what you did in OCC, and go through a demo of how to enable the feature and use the GrapesJS editor, also you can talk about the future enhancements which I'm glad to discuss with you

**Comment by hishamco** [comment]
@kudryavtsevda last week three of OCC modules demoed, I'm still encourgh you to demo the work you did in GrapesJs editor in the next stand up meeting if it's possible

**Comment by kudryavtsevda** [comment]
> @kudryavtsevda last week three of OCC modules demoed, I'm still encourgh you to demo the work you did in GrapesJs editor in the next stand up meeting if it's possible

Sorry 
I replied you in your email hishamco_2007@yahoo.com

**Comment by hishamco** [comment]
I didn't check my Yahoo email for awhile, let me check and come back to you

**Comment by hishamco** [comment]
The module is originally created by me, but polished and completed by your efforts, I appreciated the idea is you can demo it to let the OC community what you did, get the feedback also possible enhancements in the future

We can chat via gitter if you are interested ..
