### ISSUE TITLE
Page Preview Bar breaks layer rules

### ISSUE THREAD

**Issue by Piedone** [OrchardCoreContrib/OrchardCoreContrib.Modules#43]
It should rather work without it appending /preview to the path, because it breaks features that depend on the path being the original one.

E.g. this layer works as expected but breaks with the preview enabled:

![image](https://user-images.githubusercontent.com/1976647/156946228-63000fad-4b7c-4134-83e1-42dc13f2103b.png)

**Comment by hishamco** [comment]
Good point, frankly I didn't try it with Layers

**Comment by hishamco** [comment]
> It should rather work without it appending /preview to the path

Let me think if I can remove the preview slug

**Comment by hishamco** [comment]
FYI this is also not working on OC Content Preview!!

Removing the preview slug is tricky, coz I can host the previewed page, I'm still wondering why the layer doesn't show up while it's inside an iframe which contains the exact same URL?!!

**Comment by hishamco** [comment]
@Piedone I'm able to create a layer and make it works with the same rule that you added. This should be fixed in #48, as I mentioned earlier it should works fine because the page used the original URL not the modified one

Please reopen if the issue still
