### ISSUE TITLE
Enable all features with Auto Setup

### ISSUE THREAD

**Issue by Piedone** [OrchardCoreContrib/OrchardCoreContrib.Modules#44]
When you run the app, you should get a showcase of all features. Thus, enable all of them from a setup recipe, either all on a single tenant (and in that case, you don't need multiple tenants), or each on one tenant, so people can pick and choose. Add the content that's necessary to showcase the features so people can just see right away how they work.

**Comment by hishamco** [comment]
I didn't see it's right to enable all the features, especially like Page Preview Bar. Anyhow could you please let me know how to handle this via `appsettings.json` is there a section to enable some features within a tenant

**Comment by Piedone** [comment]
You need to do this form a recipe that you use as the setup recipe for Auto Setup.

**Comment by Piedone** [comment]
I didn't mean that, but rather, a recipe JSON file that you execute on setup, and which recipe you configure to be executed in appsettings. You can also permanently enable features in the root web app's `Startup` class but I wouldn't do that in this case.

**Comment by hishamco** [comment]
>  which recipe you configure to be executed in appsettings.

I didn't use recipes her, except I'm using AutoSetup from within `appsettings.json` to create the tenants automatically, I though there's a way for enabling the features too.

> You can also permanently enable features in the root web app's Startup

That's what I think about before I reply

I didn't created a recipe for setup before, do you created one in Lombiq repos?

**Comment by Piedone** [comment]
Yes, it provides flexibility.

**Comment by hishamco** [comment]
I can enable them in `Startup` if you don't mind

> Yes, it provides flexibility.

If you mean the AutoSetup configuration, please let me know how? Coz I didn't find any docs

**Comment by Piedone** [comment]
No, I still mean recipes :). It's your project so your call, but I think using `Startup` for this is the wrong approach.

**Comment by hishamco** [comment]
> No, I still mean recipes :).

lol, I got it, but how I can make it run automatically?

**Comment by Piedone** [comment]
Add a recipe to your project, reference it here: https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/blob/dev/src/OrchardCoreContrib.Modules.Web/appsettings.json#L16

**Comment by hishamco** [comment]
I see, seems I need to create a new recipe that extends the available once to make my modules enabled

**Comment by Piedone** [comment]
Just to clarify, this is super simple: you can add a recipe [like this](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/dev/src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json) that enables your features and perhaps executes the Blog recipe as well.
