### ISSUE TITLE
Add docs on how one can extend the Swagger docs

### ISSUE THREAD

**Issue by Piedone** [OrchardCoreContrib/OrchardCoreContrib.Modules#45]
As a module developer, what do I need to do to get my APIs into the Swagger docs? And after that, what do I need to do to display some nice documentation there for my API operations?

Please document under https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/blob/dev/src/OrchardCoreContrib.Apis.Swagger/README.md

**Comment by hishamco** [comment]
This is a first release, there's a plan to extend Swagger to configure it's options, please refer to #34

> what do I need to do to get my APIs into the Swagger docs?

This is good point to document

> And after that, what do I need to do to display some nice documentation there for my API operations?

I suggest to refer to Swagger or ASP.NET Core docs, your thoughts?

**Comment by Piedone** [comment]
Sounds good.

**Comment by hishamco** [comment]
Fixed in https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/commit/e54e130189f8e9e9b0083d9851e3c49b35c337d5
