### ISSUE TITLE
Impersonation accross tenant

### ISSUE THREAD

**Issue by hishamco** [OrchardCoreContrib/OrchardCoreContrib.Modules#6]
> Would it be possible to allow for an admin from the main tenant to log as admin in a sub tenant?

Quote from @agriffard, this is a very good feature to allow admin to access to sub tenants, I'm not sure if it's doable because different tenant has it's own users, furthermore this may require another page to list add the available tenants or may we can add the impersonate button in Tenants page

The challenge is to know the list of admins in each tenant, which is the first user on the tenant database, @agriffard if you have an suggestion please share it, I will try to work on this if I have a time

Thanks

**Comment by Piedone** [comment]
We've done this in this feature: https://github.com/Lombiq/Hosting-Tenants/blob/dev/Lombiq.Hosting.Tenants.Admin.Login/Readme.md

**Comment by hishamco** [comment]
Thanks Zoltan for sharing this, I saw it before but I didn't dig into that. It's time to dig in that and see what's done in that

Much appreciated

**Comment by hishamco** [comment]
I think I will close this while you already implemented this unless there's some features not implement yet

Thanks
