### ISSUE TITLE
Flag Repository with Topic of 'orchardcore'

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCoreContrib/OrchardCoreContrib.Modules#9]
Thanks for these modules! I just put up my own [Content Approval](https://github.com/jeffolmstead/Rework.ContentApproval) module and was looking how to get it connected to others in [Orchard Core Topics](https://github.com/topics/orchardcore) so we have one common place to look and found out you can do it pretty well by flagging it with an "orchardcore" "Topic". I would love to see this repository in the Orchard Core topics as there is some great work going on here. Here is an image of how you add it:

![image](https://user-images.githubusercontent.com/1848585/88786286-57e65580-d160-11ea-84bd-eb9b42dc1471.png)

Hopefully you will consider adding to the growing list of third party modules!

**Comment by hishamco** [comment]
Sorry @jeffolmstead I just forgot to reply to you, because there are tons of notifications, I just add `orchard core` topic to the repo

Thank

**Comment by hishamco** [comment]
Hope to see some of your great contributions in OCC
